name: World
greeting: en
schedule: null
email:
  enabled: false
  smtp_server: smtp.example.com
  smtp_port: 587
  sender_email: your_email@example.com
  recipient_email: recipient@example.com
  username: your_username
  password: your_password
database:
  enabled: false
  uri: sqlite:///greetings.db
web:
  enabled: false
  host: 0.0.0.0
  port: 5000
  secret_key: your_secret_key
  users:
    admin: password123
