apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app
  labels:
    app: greeting-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: greeting-app
  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
      - name: greeting-app
        image: your-dockerhub-username/greeting-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: CONFIG_PATH
          value: /app/config.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: greeting-app-service
spec:
  type: LoadBalancer
  selector:
    app: greeting-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
